server:
  port: 8080

spring:
  application:
    name: neptune-cloud-drive
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cloud_drive?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.neptune.cloud.drive
  title: neptune-cloud-drive docs
  description: neptune-cloud-drive docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: fuyusakaiori
  contact-url: https://space.bilibili.com/6074988
  contact-email: 670232228@qq.com
  version: 1.0